services:
  main-db:
    image: postgres:16.1
    container_name: mainDb
    environment:
      POSTGRES_DB: mainDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  stats-db:
    image: postgres:16.1
    container_name: statsDb
    environment:
      POSTGRES_DB: statsDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  main-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ewm-service
    container_name: ewmService
    depends_on:
      main-db:
        condition: service_healthy
    ports:
      - "8080:8080"

  stats-server:
    build:
      context: ./stats
      dockerfile: Dockerfile
    image: java-explore-with-me-stats-server
    container_name: statsApp
    depends_on:
      stats-db:
        condition: service_healthy
    ports:
      - "9090:9090"
