services:
  main-db:
    image: postgres:16.1
    container_name: main-db
    environment:
      POSTGRES_DB: mainDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mainDb"]
      interval: 10s
      timeout: 5s
      retries: 5

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    environment:
      POSTGRES_DB: statsDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d statsDb"]
      interval: 10s
      timeout: 5s
      retries: 5

  statssapp:
    build:
      context: ./ewm-stats/stats-server
      dockerfile: Dockerfile
    image: java-explore-with-me-statsapp
    container_name: statssapp
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy

  ewmservice:
    build:
      context: ./ewm-service
      dockerfile: Dockerfile
    image: java-explore-with-me-ewmservice
    container_name: ewmservice
    ports:
      - "8080:8080"
    depends_on:
      main-db:
        condition: service_healthy
