services:
  main-db:
    image: postgres:16.1
    container_name: mainDb
    environment:
      POSTGRES_DB: maindb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  stats-db:
    image: postgres:16.1
    container_name: statsDb
    environment:
      POSTGRES_DB: statsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  stats-app:
    build:
      context: ./ewm-stats/stats-server
      dockerfile: Dockerfile
    image: stats-app
    container_name: statsApp
    restart: on-failure
    depends_on:
      stats-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "9090:9090"

  ewm-service:
    build:
      context: ./ewm-service
      dockerfile: Dockerfile
    image: ewm-service
    container_name: ewm-service
    restart: on-failure
    depends_on:
      main-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8080:8080"
