# docker-compose.yml
version: '2.4'

services:
  main-db:
    image: postgres:16.1
    container_name: mainDb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: maindb
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d maindb"]
      interval: 10s
      timeout: 5s
      retries: 5

  stats-db:
    image: postgres:16.1
    container_name: statsDb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: statsdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d statsdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  stats-app:
    image: java-explore-with-me-stats-server
    container_name: statsApp
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "9090:9090"

  ewm-service:
    image: ewm-service
    container_name: ewm-service
    depends_on:
      main-db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
