services:
  mainDb:
    image: postgres:16.1
    container_name: mainDb
    environment:
      POSTGRES_DB: mainDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mainDb"]
      interval: 10s
      timeout: 5s
      retries: 5

  statsDb:
    image: postgres:16.1
    container_name: statsDb
    environment:
      POSTGRES_DB: statsDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d statsDb"]
      interval: 10s
      timeout: 5s
      retries: 5

  statsApp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: statsApp
    ports:
      - "9090:9090"
    depends_on:
      statsDb:
        condition: service_healthy

  ewmService:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ewmService
    ports:
      - "8080:8080"
    depends_on:
      mainDb:
        condition: service_healthy
