name: Docker Compose CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start containers
        run: docker-compose up -d --build

      - name: Wait for services to become healthy
        run: |
          echo "Ждем, пока контейнер ewmService станет healthy..."
          timeout 60 bash -c 'until [ "$(docker inspect -f "{{.State.Health.Status}}" ewmService)" = "healthy" ]; do sleep 2; done'

      - name: Collect container logs
        run: |
          docker-compose logs --no-color > container.log
          echo "=== Логи контейнеров ==="
          cat container.log

      - name: Upload logs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: container-logs
          path: container.log
