name: Docker CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:24.0.0
        options: --privileged

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build JAR for ewm-service
        run: mvn clean package -DskipTests -pl ewm-service -am

      - name: Build Docker image
        run: docker build -t ewm-service ./ewm-service

      - name: Start containers
        run: docker compose up -d

      - name: Wait for ewmService
        run: |
          chmod +x ./wait-for-it.sh
          ./wait-for-it.sh localhost:8080 -t 60

      - name: Show logs for ewmService if it fails
        if: failure()
        run: |
          docker logs ewmService > ewm-log.txt || true

      - name: Upload logs if failed
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ewm-log
          path: ewm-log.txt

      - name: Docker Compose PS (debug)
        run: docker compose ps

      - name: Stop containers
        if: always()
        run: docker compose down
